driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 8443, host: 8443}]
  customize:
      memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4


suites:
  - name: chef-server
    run_list:
       - recipe[vagrant-kitchen-chef-server::default]
       - recipe[chef-server::default]
    attributes:
