driver:
  name: vagrant
  network:
  - ["private_network", {ip: "33.33.33.10"}]
  customize:
      memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4


suites:
  - name: chef-server
    run_list:
       - recipe[vagrant-kitchen-chef-server::default]
       - recipe[chef-server::default]
    attributes:
