name             'vagrant-kitchen-chef-server'
maintainer       'Alex Naumchenko'
maintainer_email 'alex@devloft.com'
license          'All rights reserved'
description      'Installs/Configures vagrant-kitchen-chef-server'
long_description 'Installs/Configures vagrant-kitchen-chef-server'
version          '0.1.0'

depends 'chef-server', '~> 2.1.6'
depends 'htop'
